#!/bin/sh
if [ ! -e /dev/ttyACM0 ]
then
  echo "Couldn't open file for reading"
  exit 1
fi

fname=`date +%Y_%m_%d`.txt$1
echo "filename is "$fname
mkdir -p rides/8/
stty -F /dev/ttyACM0 raw
mkfifo myfifo
tee rides/8/$fname < /dev/ttyACM0 > myfifo&
cpid=$!
./gtkbike < myfifo
kill $cpid
rm myfifo
./bike < rides/8/$fname
